apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: testapp1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/klakshma-tenant/testapp1/testapp1@sha256:da95bc0963e2438b2650a2cef72134e07d8f6c97e4dcb18c400cb217bd20df13
        name: my-python
        resources: {}
status: {}
