apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: testapp1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testapp1
    app.kubernetes.io/part-of: testapp1
  name: testapp13uej
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: testapp1
    weight: null
status: {}
