apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: testapp1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testapp1
    app.kubernetes.io/part-of: testapp1
  name: testapp1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: testapp1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: testapp1
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/klakshma-tenant/testapp1/testapp1@sha256:da95bc0963e2438b2650a2cef72134e07d8f6c97e4dcb18c400cb217bd20df13
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
